import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amith
 */
public class GiveVote extends javax.swing.JFrame {

    /**
     * Creates new form GiveVote
     */
    public GiveVote() {
        initComponents();
        Connect();
    }
    
     Connection con;
     PreparedStatement pst;   
     ResultSet rs;
     public void Connect()  
   {
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Voting","root","amit123");
             
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(addvoters.class.getName()).log(Level.SEVERE, null, ex);
        }          
            
        
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        adhar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        vname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        village = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        voteid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        feed = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        party = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("GIVE YOUR VOTE HERE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 6, 417, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(944, 26, -1, -1));

        adhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adharActionPerformed(evt);
            }
        });
        getContentPane().add(adhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 238, 210, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Aadhar Card Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 244, -1, -1));
        getContentPane().add(vname, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 270, 210, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Voter Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 276, 160, -1));
        getContentPane().add(village, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 354, 210, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Village");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 160, -1));
        getContentPane().add(voteid, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 126, 210, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Voter Id Number");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 132, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Feedback");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 411, 160, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Sumbit Vote");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 524, -1, 40));

        feed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LOW", "GOOD", "INTERMEDIATE", "BEST", "EXCELLENT", " " }));
        getContentPane().add(feed, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 403, 210, 44));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Choose Your Party Name");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 482, -1, -1));

        party.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BJP", "RJD", "INC", "AAP", "JDU", "CPI", "BSP", "NPP", " " }));
        party.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                partyAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(party, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 474, 210, 44));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 126, 88, 40));

        setSize(new java.awt.Dimension(1076, 603));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void adharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adharActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          String vids=voteid.getText();
       
        String adhars=adhar.getText();
         String votername=vname.getText();
        String villages=village.getText();
        String feeds=feed.getSelectedItem().toString();
           String partyname=party.getSelectedItem().toString();
        
       
        try {
             pst= con.prepareStatement("insert into votingdetails(voterno,aadharno,votername,village,feed,choosepartyname) values(?,?,?,?,?,?)");
            pst.setString(1,vids);
          
            pst.setString(2,adhars);
              pst.setString(3,votername);
            pst.setString(4,villages);
            pst.setString(5,feeds);
            pst.setString(6,partyname);
            
            int k=pst.executeUpdate();
            
            if(k==1)
            {
   
                 JOptionPane.showMessageDialog(this,"Your Vote is Submitted Successfully!");
            }
            else 
            {
                JOptionPane.showMessageDialog(this ,"Record  Failed");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String voteids=voteid.getText();
        
        try{
            pst=con.prepareStatement("select votername,aadharno,village from voterinfo where voteridno=?");
            pst.setString(1, voteids);
            rs=pst.executeQuery();
            if(rs.next()){
                 adhar.setText(rs.getString( "aadharno"));
                  vname.setText(rs.getString("votername"));
                  village.setText(rs.getString("village"));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Please Enter voterid");
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void partyAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_partyAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_partyAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiveVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiveVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiveVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiveVote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiveVote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adhar;
    private javax.swing.JComboBox<String> feed;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> party;
    private javax.swing.JTextField village;
    private javax.swing.JTextField vname;
    private javax.swing.JTextField voteid;
    // End of variables declaration//GEN-END:variables
}
