import java.sql.*;  
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amith
 */
public class Registeration extends javax.swing.JFrame {

    /**
     * Creates new form Registeration
     */
    public Registeration() {
        initComponents();
    }
    Connection Con;
    PreparedStatement pst;
    ResultSet rst;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Rusername = new javax.swing.JTextField();
        Remail = new javax.swing.JTextField();
        Rmobileno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Rpassword = new javax.swing.JTextField();
        bklogin = new javax.swing.JButton();
        register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Rname, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 141, 318, 37));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText(" Registrain Application");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 471, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 138, 92, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("User Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 238, 138, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 318, 120, -1));
        getContentPane().add(Rusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 233, 318, 37));

        Remail.setText(" ");
        getContentPane().add(Remail, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 313, 318, 37));

        Rmobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmobilenoActionPerformed(evt);
            }
        });
        getContentPane().add(Rmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 393, 318, 37));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Mobile No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 398, 138, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 498, 130, -1));
        getContentPane().add(Rpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 318, 37));

        bklogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        bklogin.setText("Back To Login");
        bklogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkloginActionPerformed(evt);
            }
        });
        getContentPane().add(bklogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 597, -1, 45));

        register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        register.setText("Register ");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        getContentPane().add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 597, 150, 45));

        setSize(new java.awt.Dimension(817, 678));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bkloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkloginActionPerformed
        // TODO add your handling code here:
        Login s=new Login();
        s.hide();
        s.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_bkloginActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
        if(Rname.getText().trim().isEmpty()||Rusername.getText().trim().isEmpty()||Remail.getText().trim().isEmpty()||
            Rmobileno.getText().trim().isEmpty()||Rpassword.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this,"Please Fill Details Properly");
        }
        else{

            String RName=Rname.getText();
            String RUsername=Rusername.getText();
            String REmail=Remail.getText();
            String RMobileno=Rmobileno.getText();
            String RPassword=Rpassword.getText();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Voting","root","amit123");
                pst =Con.prepareStatement("insert into register values(?,?,?,?,?)");
                pst.setString(1,RName);
                pst.setString(2,RUsername);
                pst.setString(3, REmail);
                pst.setString(4,RMobileno);
                pst.setString(5,RPassword);

                int k= pst.executeUpdate();
                if(k==1){
                    JOptionPane.showMessageDialog(this, "Registration Succussfully");
                    Con.close();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Account Creation Fail");

                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
        }

    }//GEN-LAST:event_registerMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        //
    }//GEN-LAST:event_registerActionPerformed

    private void RmobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RmobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RmobilenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registeration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Remail;
    private javax.swing.JTextField Rmobileno;
    private javax.swing.JTextField Rname;
    private javax.swing.JTextField Rpassword;
    private javax.swing.JTextField Rusername;
    private javax.swing.JButton bklogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
